`define EMPTY  0 
`define _LUI   1 
`define _ADD   2 
`define _LW    3 
`define _OR    4 
`define _SLT   5 
`define _SLTU  6 
`define _SLL   7 
`define _SW    8 
`define _SUB   9 
`define _AND   10 
`define _NOR   11 
`define _XOR   12
`define _SRA   13
`define _SRL   14
`define _JAL   15
`define _DIV   16
`define _DIVU  17 
`define _MULT  18
`define _MULTU 19
`define _MFHI  20
`define _MFLO  21
`define _MTHI  22
`define _MTLO  23
`define _LB    24
`define _LBU   25
`define _LH    26
`define _LHU   27
`define _LWL   28
`define _LWR   29
`define _SB    30
`define _SH    31
`define _SWL   32
`define _SWR   33
`define _ERET  34
`define _MFC0  35
`define _MTC0  36
`define _ADDU  37
`define _SUBU  38
